name: hsiflutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  carousel_slider: 4.2.1
  persistent_bottom_nav_bar: 5.0.2
  intl: ^0.19.0
  flutter_svg: 2.0.9
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/logo/
    - assets/icon/
    - assets/images/
    - assets/carousel/
  uses-material-design: true

